# Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


import time
start = time.time()
# codigo

numAntes = 1
numAhora = 2
suma = 0
while numAhora < 4000000:
    if (numAhora % 2 == 0):
        suma += numAhora
    temp = numAhora
    numAhora = numAntes + numAhora
    numAntes = temp
print(suma)

# final
end = time.time()
tiempoTotal = end - start
print("TIEMPO DE EJECUCION: ", round(tiempoTotal,3),"segundos")